### ISSUE TITLE
Can someone please explain how to make the tests run

### ISSUE THREAD

**Issue by NickHarmer** [squid-box/SevenZipSharp#132]
No matter how hard I try I simply *CANNOT* make any of the tests in this project run at all.

Inside VS they just say 'Not Run':

```
No test is available in D:\projects\SevenZipSharp\Stage\Release\net45\SevenZip.Tests.dll D:\projects\SevenZipSharp\Stage\Release\net45\SevenZipSharp.dll. Make sure that test discoverer & executors are registered and platform & framework version settings are appropriate and try again.
Microsoft.VisualStudio.TestPlatform.ObjectModel.TestPlatformException: Unable to find D:\projects\SevenZipSharp\Stage\Release\netstandard2.0\testhost.dll. Please publish your test project and retry.
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Hosting.DotnetTestHostManager.GetTestHostPath(String runtimeConfigDevPath, String depsFilePath, String sourceDirectory)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Hosting.DotnetTestHostManager.GetTestHostProcessStartInfo(IEnumerable`1 sources, IDictionary`2 environmentVariables, TestRunnerConnectionInfo connectionInfo)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyOperationManager.SetupChannel(IEnumerable`1 sources, String runSettings)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyDiscoveryManager.DiscoverTests(DiscoveryCriteria discoveryCriteria, ITestDiscoveryEventsHandler2 eventHandler)
```

Publishing the project makes no difference.

From the nunit console runner with the VSProjectLoader extension loaded I just get:

```
System.ArgumentException : Invalid project file format: SevenZip.Tests.csproj
  ----> System.NullReferenceException : Object reference not set to an instance of an object.
```

Running it against the DLL just produces:

```
1) Invalid : D:\projects\SevenZipSharp\Stage\Release\netstandard2.0\SevenZip.Tests.dll
.NETStandard test assemblies are not supported by this version of the engine
```

What am I doing wrong?

**Comment by squid-box** [comment]
You can't run tests agains the netstandard2.0 dll - target the net45 dll instead.

I usually use ReSharper to run the tests, and for the AppVeyor builds the tests are invoked through OpenCover with nunitconsolerunner:

`nunit3-console.exe /domain:single Stage/Release/net45/SevenZip.Tests.dll`

**Comment by squid-box** [comment]
I recently changed the project so that the test dll is not built against Standard - so there should be a little less confusion I hope.

Closing this question due to inactivity.
