### ISSUE TITLE
compressor.CustomParameters.Add("mt", "4"); throws an error

### ISSUE THREAD

**Issue by 2021Joey** [squid-box/SevenZipSharp#136]
Hi,

this code:

```
SevenZipCompressor compressor = new SevenZipCompressor();
compressor.CompressionMode = CompressionMode.Create;
compressor.CompressionMethod = CompressionMethod.Lzma2;
compressor.CustomParameters.Add("mt", "4");
compressor.TempFolderPath = Path.GetTempPath();
compressor.ArchiveFormat = OutArchiveFormat.SevenZip;
compressor.IncludeEmptyDirectories = true;
compressor.CompressDirectory(@Quelle, @Ziel);
```

Throws an error at the line "compressor.CustomParameters.Add("mt", "4");"

> Error: System.ArgumentException: Value does not fall within the expected range.
>    at SevenZip.ISetProperties.SetProperties(IntPtr names, IntPtr values, Int32 numProperties)
>    at SevenZip.SevenZipCompressor.SetCompressionProperties()
>    at SevenZip.SevenZipCompressor.GetArchiveUpdateCallback(FileInfo[] files, Int32 rootLength, String password)
>    at SevenZip.SevenZipCompressor.CompressFilesEncrypted(Stream archiveStream, Int32 commonRootLength, String password, String[] fileFullNames)
>    at SevenZip.SevenZipCompressor.CompressDirectory(String directory, Stream archiveStream, String password, String searchPattern, Boolean recursion)
>    at SevenZip.SevenZipCompressor.CompressDirectory(String directory, String archiveName, String password, String searchPattern, Boolean recursion)
>    at ForensicZip.Program.CreateZip() in D:\Entwicklung\CSharp\Forensic7Zip\Forensic7Zip\Program.cs:line 318

compressor.CustomParameters.Add("mt", "on"); or 
compressor.CustomParameters.Add("mt", "off");
works fine, but if i want to specify the number of Threads i want to use for compression (4 for example), it throws that error...

Is there a way to specify the number of threads for compression or i am doing something wrong?

Cmd-Line-7Z-Parameter is -mt=4

Thanks for help!

**Comment by squid-box** [comment]
Sorry for the delay, but this is definitely a bug in my implementation. SevenZipSharp currently handles the `mt` property as a string (on/off), but it needs to detect and properly handle if an integer is passed.

Should be a fairly easy fix, but I can't promise when I'll have time to do a new release.

**Comment by 2021Joey** [comment]
Thanks for the answer!
A fix would be very nice, MT one of the most important Parameters...:-)

Would be great if you can fix this!
Thanks!

**Comment by squid-box** [comment]
Please give 1.5.0 a try and see if it solves your issue. I'll leave this issue open for a while.

**Comment by MayMih** [comment]
Tested with version 1.5.0.366 - works ok.
`_compressor.CustomParameters.Add("mt", Environment.ProcessorCount.ToString());`
