### ISSUE TITLE
Execution has failed due to an internal SevenZipSharp issue (0x8007000e)

### ISSUE THREAD

**Issue by agoudemez** [squid-box/SevenZipSharp#53]
A exception is throw when we want to compress a large number of files (900 files - approximately 1Mo Each)

This is the stack trace :

`   at SevenZip.SevenZipBase.ThrowException(CallbackBase handler, Exception[] e)
   at SevenZip.SevenZipBase.CheckedExecute(Int32 hresult, String message, CallbackBase handler)
   at SevenZip.SevenZipCompressor.CompressStreamDictionary(IDictionary`2 streamDictionary, Stream archiveStream, String password)
   at SevenZip.SevenZipCompressor.CompressFileDictionary(IDictionary`2 fileDictionary, Stream archiveStream, String password)
   at SevenZip.SevenZipCompressor.CompressFileDictionary(IDictionary`2 fileDictionary, String archiveName, String password)`

- release number : 1.2.184.0
- 7z version used : 18.5.0.0 (64bits)
- OS : Windows Server 2012 R2 (EN - 64 bits)

The working workaround is to do a compression call each 100 files.

**Comment by squid-box** [comment]
The error code 0x8007000e corresponds to `E_OUTOFMEMORY` - what amount of RAM do you have on the device running the compression? If you look at the memory usage of the process, does it seem unreasonably large?

**Comment by agoudemez** [comment]
There is 4Gb of memory on the server (it is a QA server).

I have done a test today, try the compression of IIS log files (7517 files - 24.4 GB) :

- 28% used memory before the process start
- around 70% used memory when the 0x8007000e error raise.

The raised error :

`SevenZip.SevenZipException: Execution has failed due to an internal SevenZipSharp issue (0x8007000e).
Please report it to https://github.com/squid-box/SevenZipSharp/issues/, include the release number, 7z version used, and attach the archive.
   at SevenZip.SevenZipBase.ThrowException(CallbackBase handler, Exception[] e)
   at SevenZip.SevenZipBase.CheckedExecute(Int32 hresult, String message, CallbackBase handler)
   at SevenZip.SevenZipCompressor.CompressStreamDictionary(IDictionary 2 streamDictionary, Stream archiveStream, String password)
   at SevenZip.SevenZipCompressor.CompressFileDictionary(IDictionary 2 fileDictionary, Stream archiveStream, String password)
   at SevenZip.SevenZipCompressor.CompressFileDictionary(IDictionary 2 fileDictionary, String archiveName, String password)`

I was using my workaround (a compression each 100 files) and the error raised at the 3th step

Don't hesitate if you need more informations.

**Comment by agoudemez** [comment]
I have changed a little bit the workaround and forced the SevenZipCompressor object to be recreated at each loop. (and compressor = null and the end of the loop)

Which this workaround, I don't have 0x8007000e error but the memory reach 100% of usage :

![image](https://user-images.githubusercontent.com/708048/63364764-85cef180-c376-11e9-866f-3db8d03a6654.png)
